version: '2.3'
services:
  ## for some linux dist, you may get the error,
  ## please check https://github.com/scylladb/scylla/issues/5638 it first
  ## summary ops for the link:
  ## set `fs.aio-max-nr = 1048576` in /etc/sysctl.conf
  ## then exec `sudo sysctl -p`
  tushare-scylla:
    image: scylladb/scylla:3.1.1
    container_name: tushare-scylla
    command:
      - "--smp"
      - "2"
    mem_limit: 2GB
    ports:
      - "9042:9042"
    volumes:
      - ./tmp/tushare-scylla:/var/lib/scylla